### PR TITLE
[COOK-4665] - Improve the handling of unspecified configuration options in socketproxy apps

### PR DESCRIPTION
**Pull request by eherot**

### CODE REVIEW

**Comment by jeffbyrnes** [comment]
@eherot looks like this needs a rebase to become mergeable again.

**Comment by miketheman** [comment]
It also appears to break any existing behaviors - since the attribute names have been changed. I'd rather not incorporate any breaking changes before releasing 2.7.5.

**Comment by jeffbyrnes** [comment]
@miketheman ah, good thing to point out. Might make sense to just discard this, in that cast. I'll leave that determination up to @eherot.

**Comment by eherot** [comment]
Fixed the merge conflict.

At any rate, @miketheman, unless I've made a mistake here this should not actually introduce any breaking changes as `node['nginx']['socketproxy']['apps']` is actually still used as the definitive hash to define applications, I just added a "defaults" hash that gets merged in the recipe if apps is empty (previously it just used to error out if apps was undefined and I didn't want that).

**Comment by eherot** [comment]
In light of a495ee64 I will certainly not take it personally if you opt not to merge this as I whole-heartedly support that effort and I wouldn't want to do anything to further complicate it.

That said, this was intended to fix a bug (albeit one reported by yours truly).

 Also if you need/want my help in porting the socketproxy feature to 3.0.0, please don't hesitate to ask.

**Pull request closed without merging**
