### PR TITLE
Fix berks deps

### LINKED ISSUE #412: BerkShelf showing conflict error when installing package with 2.7.6
Berkshelf fails to install version of nginx cookbook newer then 1.8.0. 

Receive the following error. If I remove the nginx statement it works fine. 

Unable to satisfy constraints on package nginx due to solution constraint (nginx = 2.7.6). Solution constraints that may result in a constraint on nginx: [(nginx = 2.7.6)]
Demand that cannot be met: (nginx = 2.7.6)
Artifacts for which there are conflicting dependencies: nginx = 1.8.0 -> [(build-essential >= 0.0.0), (yum >= 0.0.0), (apt >= 0.0.0), (runit >= 0.0.0), (ohai >= 1.1.4)]Unable to find a solution for demands: apt (3.0.0), ark (1.0.1), ax-elasticsearch (0.1.0), build-essential (3.2.0), chef-client (4.3.3), chef-solo-search (0.5.1), chef-sugar (3.3.0), chef_handler (1.3.0), compat_resource (12.9.0), cron (1.7.6), elasticsearch (2.2.2), homebrew (2.1.0), iptables (2.2.0), java (1.39.0), logrotate (1.9.2), memcached (2.1.0), mysql (6.1.3), mysql-ct (0.1.1), nodejs (2.4.4), ntp (1.11.0), openssh (1.3.4), packagecloud (0.2.0), rbac (1.0.3), redisio (2.3.0), runit (1.7.6), seven_zip (2.0.0), sftp (1.0.10), sinopia (0.3.4), smf (2.2.8), ulimit (0.3.3), user (0.4.2), users (1.7.0), windows (1.39.2), yum (3.10.0), yum-epel (0.6.6), yum-mysql-community (0.2.0), nginx (= 2.7.6)

### PR DESCRIPTION
**Pull request by jdoss**
This PR fixes #412 as it was blocking me from using Nginx on a new deployment. I tested it on Fedora 24.

---
This change is [Reviewable](https://reviewable.io/reviews/miketheman/nginx/418)

### CODE REVIEW

**Comment by legal90** [comment]
+1. While other community cookbooks are updating, `nginx` looks stuck for more than 1 year. That makes this cookbook unusable for many cases due to version conflicts. 
I think it's reasonable to update the dependency constraints (or remove them at all, like in this PR) and release the next 2.7.* version

@miketheman Please, take a look. The community really needs this.

**Comment by tas50** [comment]
This has been rolled into #422

**Comment by jdoss** [comment]
Cool! Thanks for including my PR. :D

**Comment by tas50** [comment]
This particular issue has been pulled into the chef_nginx cookbook 2.8.0 release. The chef_nginx cookbook is a fork of this cookbook with many of the outstanding issues in the 2.7.6 release resolved. The release is backwards compatible with this cookbook outside of the name change, which obviously requires updating runlist and and metadata dependencies. I'd highly suggest giving it a try to see if this resolves you nginx cookbook woes.

https://github.com/chef-cookbooks/chef_nginx
https://supermarket.chef.io/cookbooks/chef_nginx#changelog

**Pull request closed without merging**
